### ISSUE TITLE
Add topic: terminal-share

### ISSUE THREAD

**Issue by katrinleinweber** [streamhut/streamhut#10]
Thanks for publishing this! How about adding it to [GitHub.com/topics/terminal-share](https://github.com/topics/terminal-share) alongside similar tools by [adding that topic](https://help.github.com/articles/about-topics/) to this repo? Thank you :-)

**Comment by miguelmota** [comment]
Topic `terminal-share` has been added.

**Comment by katrinleinweber** [comment]
Awesome, thank you :-)
